services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./back-end:/var/www/back-end
      - ./front-end:/var/www/front-end
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.2
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: y13_occompare
      POSTGRES_USER: default
    volumes:
      - "db:/var/lib/postgresql"
  redis:
    image: redis
volumes:
  db:
  redis: